#!/usr/bin/Rscript


wb <- createWorkbook()

csHead <- CellStyle(wb) + Font(wb, isBold=TRUE) + Border()  # header
csGroup <- CellStyle(wb) + Font(wb, isBold = TRUE , isItalic = TRUE ) + Border()  # header


sheet  <- createSheet(
    wb = wb ,
    sheetName="Overview")


nRow <- 3


addDataFrame(
    x = data.frame(
        Study = JSON$Population$Label
    ) ,
    sheet = sheet ,
    startRow = nRow ,
    startColumn = 2 ,
    colnamesStyle = csHead)
nRow <- nRow + 3


addDataFrame(
    x = data.frame(
        Patients = sapply( JSON$Population$Subset , with , Comment )
    ) ,
    sheet = sheet ,
    startRow = nRow ,
    startColumn = 2 ,
    colnamesStyle = csHead)
nRow <- nRow + length( sapply( JSON$Population$Subset , with , Comment )) + 2


addDataFrame(
    x = data.frame(
        Endpoints = sapply( JSON$Survival$Endpoints , with , Label )
    ) ,
    sheet = sheet ,
    startRow = nRow ,
    startColumn = 2 ,
    colnamesStyle = csHead)
nRow <- nRow + length( Events ) + 2


addDataFrame(
    x = data.frame(
        Predictors = sapply( JSON$Survival$Predictors , with , Label )
    ) ,
    sheet = sheet ,
    startRow = nRow ,
    startColumn = 2 ,
    colnamesStyle = csHead)
nRow <- nRow + length( Predictors ) + 2


addDataFrame(
    x = data.frame(
        Modifiers = sapply( JSON$Survival$Modifiers , with , Label )
    ) ,
    sheet = sheet ,
    startRow = nRow ,
    startColumn = 2 ,
    colnamesStyle = csHead)
nRow <- nRow + length( Modifiers ) + 2

