#!/usr/bin/Rscript


for (n.CG in 1:length(CGs)) {

    PCFileName <- gsub(

        pattern = " " ,

        replacement = "" ,

        x = paste(
            "15-PatientCharacteristics",
            sapply( JSON$Characteristics$Groups , with , ShortLabel )[n.CG] ,
            sep = "-" )
    )

    knit2html(

        input = paste(
            HOME_DIR ,
            "15_Patient_Characteristics.Rmd" ,
            sep = "/" ) ,
        
        output = paste(
            PCFileName ,
            "md" ,
            sep = "." )
        
    )
    
}


