#!/usr/bin/Rscript


    # close the Excel file
wb <- loadWorkbook(
    file = "Result-Tables.xlsx" ) 

csHead <- CellStyle(wb) + Font(wb, isBold=TRUE) + Border()  # header
csGroup <- CellStyle(wb) + Font(wb, isBold = TRUE , isItalic = TRUE ) + Border()  # header


for (n.CG in 1:length(CGs)) {

    
    PCFileName <- gsub(

        pattern = " " ,

        replacement = "" ,

        x = paste(
            "PatientCharacteristics",
            sapply( JSON$Characteristics$Groups , with , ShortLabel )[n.CG] ,
            sep = "-" )
    )

    
    knit2html(

        input = paste(
            HOME_DIR ,
            "Patient_Characteristics.Rmd" ,
            sep = "/" ) ,
        
        output = paste(
            PCFileName ,
            "md" ,
            sep = "." ) ,
        
        options = c("use_xhtml","smartypants","mathjax","highlight_code","fragment_only")
    )

    
    sheet  <- createSheet(
        wb = wb ,
        sheetName = PCFileName
    )
    
    addDataFrame(
        x = cbind("Categories","Percent","Count","Percent","Count","Percent","Count","Percent","Count","P-value") ,
        sheet = sheet ,
        row.names = FALSE ,
        col.names = FALSE ,
        startRow = 3 ,
        startCol = 1 ,
        colStyle = list('1'=csGroup))

    addDataFrame(
        x = Table1Proportions ,
        sheet = sheet ,
        col.names = FALSE ,
        startRow = 3 ,
        colnamesStyle = csHead)
    nRow <- 5 + dim( Table1Proportions )[1]

    
    addDataFrame(
        x = cbind("Measurements","Mean","SE","Mean","SE","Mean","SE","Mean","SE","P-value") ,
        sheet = sheet ,
        row.names = FALSE ,
        col.names = FALSE ,
        startRow = nRow ,
        colStyle = lapply(1:10,function(X)return(csGroup)))
    nRow <- nRow + 1

    addDataFrame(
        x = Table1Means ,
        sheet = sheet ,
        col.names = FALSE ,
        startRow = nRow ,
        colnamesStyle = csHead)
    nRow <- nRow + dim( Table1Means )[1] + 2

    
    addDataFrame(
        x = cbind("Measurements","Median","SE","Median","SE","Median","SE","Median","SE","P-value") ,
        sheet = sheet ,
        row.names = FALSE ,
        col.names = FALSE ,
        startRow = nRow ,
        colStyle = list('1'=csGroup))
    nRow <- nRow + 1

    addDataFrame(
        x = Table1Medians ,
    sheet = sheet ,
    col.names = FALSE ,
    startRow = nRow ,
    colnamesStyle = csHead)
    
}


    # close the Excel file
saveWorkbook(
    wb = wb ,
    file = "Result-Tables.xlsx" ) 
