#!/usr/bin/Rscript


for (n.Surv in 1:length(Es)) {

    for (n.P in 1:length(Ps)) {

            # Build the name of the outfile from the
            # endpoint, predictor, modifier combination:

        SurvivalFileName <- gsub(
            " " , "" ,
            paste(
                "20" ,
                "Survival" ,
                sapply( JSON$Survival$Endpoints , with , ShortLabel )[n.Surv] ,
                sapply( JSON$Survival$Predictors , with , ShortLabel )[n.P] ,
                sep = "-" ))

        SurvivalOutfile <- paste(
            SurvivalFileName ,
            ".md" ,
            sep = "" )
        
        opts_chunk$set(
            fig.path = paste("./figure/" , SurvivalFileName , "-" , sep = "" ))

        knit(

            input = paste(
                HOME_DIR ,
                "20_Survival_Predictor.Rmd" ,
                sep = "/" ) ,

            output = SurvivalOutfile
        )
        

        
        for (n.M in 1:length(Ms)) {

            # Build the name of the outfile from the
            # endpoint, predictor, modifier combination:
            
            InteractionFileName <- gsub(
                " " , "" ,
                paste(
                    "20" ,
                    "Survival" ,
                    sapply( JSON$Survival$Endpoints , with , ShortLabel )[n.Surv] ,
                    sapply( JSON$Survival$Predictors , with , ShortLabel )[n.P] ,
                    sapply( JSON$Survival$Modifiers , with , ShortLabel )[n.M] ,
                    sep = "-" ))

            opts_chunk$set(
                fig.path = paste("./figure/" , InteractionFileName , "-" , sep = "" ))
            
            InteractionOutfile <- paste(
                InteractionFileName ,
                ".md" ,
                sep = "" )

            knit(
                input = paste(
                    HOME_DIR ,
                    "20_Survival_Predictor_Modifier.Rmd" ,
                    sep = "/" ) ,
                output = InteractionOutfile
                )

            
            if (
                ( sapply( JSON$Survival$Predictors , with , Type )[n.P] == "numeric" ) &
                ( sapply( JSON$Survival$Modifiers , with , Type )[n.M] == "numeric" )
            ) {

                GAM3dOutfile <- paste(
                    InteractionFileName ,
                    "-3d.md" ,
                    sep = "" )

                knit(
                    input = paste(
                        HOME_DIR ,
                        "20_Survival_Predictor_Modifier_WebGL.Rmd" ,
                        sep = "/" ) ,
                    output = GAM3dOutfile
                    )
                
                }
            }
        }
    }
