


## 3d-GAM

Surface spline of `r sapply( JSON$Survival$Endpoints , with , Label )[n.Surv]` incidence by empirical percentiles of `r sapply( JSON$Survival$Predictors , with , Label )[n.P]` and `r sapply( JSON$Survival$Modifiers , with , Label )[n.M]` estimated with a Generalized Additve Model.



```{r SurfaceSpline,include=FALSE}

Fq <- as.formula( paste( "E" , n.Surv-1 , "~s(qP" , n.P-1 , ",qM" , n.M-1 , ")" , sep = "" ))

GAMq <- gam(
    formula = Fq ,
    data = D ,
    family = "binomial")

Mq <- data.frame(
    x = GAMq$model[ , paste( "qP" , n.P-1 , sep = "" )] ,
    y = GAMq$model[ , paste( "qM" , n.M-1 , sep = "" )] ,
    z = 100 * as.numeric( predict( GAMq , type = "response" )) ,
    event = GAMq$model[ , paste( "E" , n.Surv-1 , sep = "" )]
)


Fz <- as.formula( paste( "E" , n.Surv-1 , "~s(zlogP" , n.P-1 , ",zlogM" , n.M-1 , ")" , sep = "" ))

GAMz <- gam(
    formula = Fz ,
    data = D ,
    family = "binomial")

Mz <- data.frame(
    x = GAMz$model[ , paste( "zlogP" , n.P-1 , sep = "" )] ,
    y = GAMz$model[ , paste( "zlogM" , n.M-1 , sep = "" )] ,
    z = 100 * as.numeric( predict( GAMz , type = "response" )) ,
    event = GAMz$model[ , paste( "E" , n.Surv-1 , sep = "" )]
)

``` 


```{r WebGLq,results='as.is'}

options( rgl.useNULL = TRUE )

plot3d(
    Mq ,
    type = "s" ,
    radius = 0.5 ,
    xlab = sapply( JSON$Survival$Predictors , with , Label )[n.P] ,
    ylab = sapply( JSON$Survival$Modifiers , with , Label )[n.M] ,
    zlab = sapply( JSON$Survival$Endpoints , with , Label )[n.Surv] ,
    col = abs( Mq$event - 3 ))

rglwidget(
    elementId = "GAM-3d-qPxqM-rgl"
)

``` 





```{r WebGLz,results='as.is'}

plot3d(
    Mz ,
    xlim = c(-2,2) ,
    ylim = c(-2,2) ,
    type = "s" ,
    radius = 0.2 ,
    xlab = sapply( JSON$Survival$Predictors , with , Label )[n.P] ,
    ylab = sapply( JSON$Survival$Modifiers , with , Label )[n.M] ,
    zlab = sapply( JSON$Survival$Endpoints , with , Label )[n.Surv] ,
    col = abs( Mz$event - 3 ))

rglwidget(elementId="GAM-3d-zlogPxzlogM-rgl",reuse = TRUE)

``` 


```{r VisGAMz,fig.width=6,fig.height=6,out.width="600pt"}

vis.gam(
    x = GAMz ,
    n.grid = 50 ,
    color = "terrain" ,
    type = "response" ,
    xlab = sapply( JSON$Survival$Predictors , with , Label )[n.P] ,
    ylab = sapply( JSON$Survival$Modifiers , with , Label )[n.M] ,
    zlab = "Incidence" ,
    phi = 0 ,
    theta = -20 ,
    ticktype = "detailed"
)

``` 


      
```{r VisGAMzSE,fig.width=6,fig.height=6,out.width="600pt"}

vis.gam(
    x = GAMz ,
    n.grid = 50 ,
    se = TRUE ,
    type = "response" ,
    xlab = sapply( JSON$Survival$Predictors , with , Label )[1] ,
    ylab = sapply( JSON$Survival$Modifiers , with , Label )[1] ,
    zlab = "Incidence" ,
    phi = 0 ,
    theta = -20 ,
    ticktype = "detailed"
)
    
``` 
