#!/usr/bin/Rscript

   # for testing:
   # tmp <- tempdir();system2( "cp" , c("report.json",tmp)); setwd(tmp)


args<-commandArgs(TRUE)
options( width="130")


HOME_DIR <- "/home/rforge/Documents/github/norcad"

   # load packages

require(knitr)
require(htmlTable)
require(rgl)
require(rglwidget)
require(Hmisc)

require(smcfcs)
require(purrr)

require(survival)
require(quantreg)
require(mgcv)
require(xlsx)


   # prepare knitr

opts_chunk$set(
    warnings=FALSE,
    echo=FALSE,
    dpi = 300 ,
    dev="svg")


   # load all R functions from the directory
lapply(
    X = dir(
        paste(
            HOME_DIR ,
            "functions" ,
            sep = "/")) ,
    FUN = function(X) source(
                          paste(
                              HOME_DIR ,
                              "functions" ,
                              X ,
                              sep = "/"))) -> DoNotPrint


   # run all R scripts in HOME_DIR/modules/
lapply(
    X = dir(
        paste(
            HOME_DIR ,
            "modules" ,
            sep = "/")) ,
    FUN = function(X) source(
                          paste(
                              HOME_DIR ,
                              "modules" ,
                              X ,
                              sep = "/"))) -> DoNotPrint

# source( "/home/rforge/Documents/github/norcad/modules/" )
