

# Patient baseline characteristics
## over `r sapply( JSON$Characteristics$Groups , with , Label )[n.P]`


```{r,PCgetAllVars,include=FALSE}

# n.P <- 1 ; n.M <- 1 ; n.Surv <- 1
opts_chunk$set(warnings=FALSE,echo=FALSE,errors=FALSE)

Table1Vars   <- c(As,CMs)
Table1Types  <- sapply(c(JSON$Survival$Adjustments,JSON$Characteristics$Measures) , with , Type )
Table1Labels <- sapply(c(JSON$Survival$Adjustments,JSON$Characteristics$Measures) , with , Label )

 # set the description of the grouping variables according to the type of
 # the grouping variable: numeric -> quartiles , factor -> groups
GroupChar <- if( sapply( JSON$Characteristics$Groups , with , Type )[n.P] == "numeric" ) {
                 paste ( sapply( JSON$Characteristics$Groups , with , Label )[n.P] , "quartiles")
                 } else {
                 paste ( sapply( JSON$Characteristics$Groups , with , Label )[n.P] , "groups")
                 }

CgroupLabels <- if( sapply( JSON$Characteristics$Groups , with , Type )[n.P] == "numeric" ) {
                   c( levels( D[ , paste( "cP" , n.P-1 , sep = "" )]) , "" )
                   } else {
                   c( unlist(sapply( JSON$Characteristics$Groups , with , ValueLabels )) , "" )
                   }

``` 



## Proportions

```{r,LaTeXproportions,results='as.is'}

Table1Proportions <- matrix(
    unlist(
        lapply(
            X = paste( Table1Vars[which(Table1Types == "factor")] ) ,
            FUN = ProportionsOverGroups ,
            groups = paste("cCG" , n.P-1 , sep = "" ))
        ) ,
    ncol = 9 ,
    byrow = TRUE
)


htmlTable(
          Table1Proportions,
          header =  c("%","N","%","N","%","N","%","N","P"),
          rnames = Table1Labels[which(Table1Types == "factor")] ,
          n.cgroup = c(2,2,2,2,1), 
          cgroup = CgroupLabels ,
          caption = paste(
                  "Patient characteristics over" , GroupChar ,
                  "for categorical variables reported as proportions (counts); " ,
                  "Standard errors and p for trend where estimated with logistic regression models.") ,
          tfoot="")

``` 

    

## Means    

```{r,LaTeXMeans}

Table1Means <- matrix(
    unlist(
        lapply(
            X = paste( Table1Vars[which(Table1Types == "numeric")] ) ,
            FUN = MeansOverGroups ,
            groups = paste("cCG" , n.P-1 , sep = "" ))
        ) ,
    ncol = 9 ,
    byrow = TRUE
)


htmlTable(
          Table1Means ,
          header =  c( "Mean","SE","Mean","SE","Mean","SE","Mean","SE","P" ),
          rnames = Table1Labels[which(Table1Types == "numeric")] ,
          cgroup = CgroupLabels ,
          n.cgroup = c(2,2,2,2,1) , 
          caption = paste(
                  "Patient characteristics over" ,
                  GroupChar ,
                  "for continuous variables reported as mean (standard error);" ,
                  "standard errors and p for trend were estimated with general linear models.") ,
          tfoot = "")

```
    

## Medians

```{r,LaTeXMedians}

Table1Medians <- matrix(
    unlist(
        lapply(
            X = paste( Table1Vars[which(Table1Types == "numeric")] ) ,
            FUN = MediansOverGroups ,
            groups = paste("cCG" , n.P-1 , sep = "" ))
        ) ,
    ncol = 9 ,
    byrow = TRUE
)

htmlTable(
          Table1Medians ,
          header =  c( "Median","SE","Median","SE","Median","SE","Median","SE","P" ),
          rnames = Table1Labels[which(Table1Types == "numeric")] ,
          cgroup = CgroupLabels ,
          n.cgroup = c(2,2,2,2,1) , 
          caption = paste(
                          "Patient characteristics over" ,
                          GroupChar ,
                          "for continuous variables reported as median (standard error);" ,
                          "standard errors and p for trend were estimated with median regression models.") ,
          tfoot="")

``` 
